{{- if or .Values.opencost.cloudIntegrationJSON .Values.opencost.cloudCost.yandex.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opencost.cloudIntegration.secretName" . }}
  namespace: {{ include "opencost.namespace" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
data:
  {{- if .Values.opencost.cloudCost.yandex.enabled }}
  cloud-integration.json: {{ include "opencost.yandexCloud.usageJSON" . | b64enc | quote }}
  {{- else }}
  cloud-integration.json: {{ .Values.opencost.cloudIntegrationJSON | trimSuffix "\n" | b64enc | quote }}
  {{- end }}
{{- end }}
