{{- $yc := .Values.opencost.exporter.yandexCloud -}}
{{- if and $yc.enabled $yc.serviceAccountKey.value (not $yc.serviceAccountKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencost.yandexCloud.secretName" . }}
  namespace: {{ include "opencost.namespace" . }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $yc.serviceAccountKey.secretKey }}: {{ $yc.serviceAccountKey.value | toString | trimSuffix "\n" | b64enc | quote }}
{{- end }}
